version: '3.8'
services:
  app:
    build: .
    container_name: blog-app
    ports:
      - "9000:9000"
    env_file:
      - .env.docker
    depends_on:
      blog-db:
        condition: service_healthy
    restart: always

  blog-db:
    image: mysql:9.2.0
    container_name: blog-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: springblog
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
