services:
  app:
    build: .
    container_name: blog-app
    ports:
      - "9000:9000"
    env_file:
      - .env  # Carga las variables del archivo .env
    restart: always
    depends_on:
      blog-db:
        condition: service_healthy


  blog-db:
    image: mysql:9.2.0
    container_name: blog-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: springblog
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
