server:
  port: 9000
  servlet:
    context-path: /api


spring:
  application:
    name: roomly-services
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springblog
    username: admin
    password: 1234
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:testdb
#        username: sa
#        password: sa